# Generated by Django 3.2.5 on 2021-07-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxy',
            name='star_system',
        ),
        migrations.RemoveField(
            model_name='starsystem',
            name='planet',
        ),
        migrations.RemoveField(
            model_name='starsystem',
            name='star',
        ),
    ]
