# Generated by Django 3.2.5 on 2021-07-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarSystem', '0002_auto_20210725_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galaxy',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Galaxies'},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['star_system'], 'verbose_name_plural': 'Planets'},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['star_system'], 'verbose_name_plural': 'Stars'},
        ),
        migrations.AlterModelOptions(
            name='starsystem',
            options={'ordering': ['galaxy'], 'verbose_name_plural': 'StarSystems'},
        ),
    ]
