# Generated by Django 3.2.5 on 2021-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarSystem', '0004_rename_live_planet_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='life',
            field=models.BooleanField(default=False),
        ),
    ]
